<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-01-20 21:11
=======
# Generated by Django 3.1.4 on 2021-01-20 20:35
>>>>>>> 2af186c88d3d083b840152ec6491eef229f2256a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rutUsuario', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=45)),
                ('staff', models.BooleanField()),
                ('usuario', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilLipidico',
            fields=[
                ('id_plipidico', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_plipidico', models.DateTimeField()),
                ('nombre_plipidico', models.CharField(default='Examen de Perfil Lipidico', max_length=30)),
                ('colesterol', models.DecimalField(decimal_places=1, max_digits=4)),
                ('colesterol_ldl', models.DecimalField(decimal_places=1, max_digits=4)),
                ('colesterol_hdl', models.DecimalField(decimal_places=1, max_digits=4)),
                ('trigliceridos', models.DecimalField(decimal_places=1, max_digits=4)),
                ('observacion_plipidico', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilBioquimico',
            fields=[
                ('id_pbioquimico', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_pbioquimico', models.DateTimeField()),
                ('nombre_pbioquimico', models.CharField(default='Examen de Perfil Bioquimico', max_length=30)),
                ('glucosa', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nitrogeno_ureico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('calcio', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fosforo', models.DecimalField(decimal_places=1, max_digits=4)),
                ('proteinas_totales', models.DecimalField(decimal_places=1, max_digits=4)),
                ('albumina', models.DecimalField(decimal_places=1, max_digits=4)),
                ('colesterol_total', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acido_urico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fosfatas_alcalinas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bilirrubina_total', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ldh', models.DecimalField(decimal_places=1, max_digits=4)),
                ('got_ast', models.DecimalField(decimal_places=1, max_digits=4)),
                ('creatinina', models.DecimalField(decimal_places=1, max_digits=4)),
                ('observaciones_pbioquimico', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Orina',
            fields=[
                ('id_orina', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_orina', models.DateTimeField()),
                ('nombre_orina', models.CharField(default='Examen de Orina', max_length=30)),
                ('color', models.CharField(max_length=25)),
                ('densidad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('glucosa', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cetonas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('urobilinogeno', models.DecimalField(decimal_places=1, max_digits=4)),
                ('billirubina', models.DecimalField(decimal_places=1, max_digits=4)),
                ('observaciones_orina', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Hemograma',
            fields=[
                ('id_hemograma', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_hemograma', models.DateTimeField()),
                ('nombre_hemograma', models.CharField(default='Examen de Hemograma', max_length=30)),
                ('eritrocito', models.DecimalField(decimal_places=1, max_digits=4)),
                ('leucocitos', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hemoglobina', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hematocrito', models.DecimalField(decimal_places=1, max_digits=4)),
                ('vcm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chcm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('plaquetas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('observaciones_hemograma', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Glicemia',
            fields=[
                ('id_glicemia', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_glicemia', models.DateTimeField()),
                ('nombre_glicemia', models.CharField(default='Examen de Glicemia', max_length=30)),
                ('glicemia_basal', models.DecimalField(decimal_places=1, max_digits=4)),
                ('glicemia_120min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('observaciones_glicemia', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('fecha_diagnostico', models.DateTimeField(default=None, primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Coagulacion',
            fields=[
                ('id_coagulacion', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_coagulacion', models.DateTimeField()),
                ('nombre_coagulacion', models.CharField(default='Examen de Coagulacion', max_length=30)),
                ('tiempo_protrombina', models.DecimalField(decimal_places=1, max_digits=4)),
                ('porc_protrombina', models.DecimalField(decimal_places=1, max_digits=4)),
                ('observaciones_coagulacion', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
    ]
