# Generated by Django 3.1.4 on 2021-01-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coagulacion',
            old_name='fecha_coagulacion',
            new_name='fecha_solicitud',
        ),
        migrations.RenameField(
            model_name='coagulacion',
            old_name='nombre_coagulacion',
            new_name='nombre_examen',
        ),
        migrations.RenameField(
            model_name='glicemia',
            old_name='nombre_glicemia',
            new_name='nombre_examen',
        ),
    ]
