# Generated by Django 3.1.5 on 2021-01-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha_diagnostico',
            field=models.DateField(default=None, primary_key=True, serialize=False),
        ),
    ]
