# Generated by Django 2.2.17 on 2021-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfillipidico',
            name='fecha_plipidico',
            field=models.DateField(),
        ),
    ]
