# Generated by Django 3.1.4 on 2021-01-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rutUsuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
