# Generated by Django 3.1.4 on 2021-01-21 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coagulacion',
            name='nombre_examen',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5, 'Error, el nombre del examen debe contar con mas de 5 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, el nombre del examen debe contar con menos de 15 caracteres')]),
        ),
        migrations.AlterField(
            model_name='coagulacion',
            name='observaciones_coagulacion',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10, 'Error, la observacion debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(150, 'Error, la observacion debe contar con menos de 150 caracteres')]),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='diagnostico',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(5, 'Error, el diagnostico debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(40, 'Error, el diagnostico debe contar con menos de 10 caracteres')]),
        ),
        migrations.AlterField(
            model_name='glicemia',
            name='nombre_examen',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10, 'Error, la observacion debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, la observacion debe contar con menos de 15 caracteres')]),
        ),
        migrations.AlterField(
            model_name='glicemia',
            name='observaciones_glicemia',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, 'Error, la observacion debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(150, 'Error, la observacion debe contar con menos de 150 caracteres')]),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='nombre_hemograma',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'Error, el nombre hemograma debe contar con mas de 5 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, el nombre hemogram debe contar con menos de 15 caracteres')]),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='observaciones_hemograma',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10, 'Error, la observacion debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(150, 'Error, la observacion debe contar con menos de 150 caracteres')]),
        ),
        migrations.AlterField(
            model_name='orina',
            name='color',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5, 'Error, el color debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, el color debe contar con menos de 15 caracteres')]),
        ),
        migrations.AlterField(
            model_name='orina',
            name='nombre_orina',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10, 'Error, el nombre de la orina debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, el nombre de la orina debe contar con menos de 15 caracteres')]),
        ),
        migrations.AlterField(
            model_name='orina',
            name='observaciones_orina',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, 'Error, la observacion debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(150, 'Error, la observacion debe contar con menos de 150 caracteres')]),
        ),
        migrations.AlterField(
            model_name='perfilbioquimico',
            name='nombre_pbioquimico',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Error, el nombre pbioquimico debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(10, 'Error, el nombre pbioquimico debe contar con menos de 10 caracteres')]),
        ),
        migrations.AlterField(
            model_name='perfilbioquimico',
            name='observaciones_pbioquimico',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10, 'Error, la observacion debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(150, 'Error, la observacion debe contar con menos de 150 caracteres')]),
        ),
        migrations.AlterField(
            model_name='perfillipidico',
            name='nombre_plipidico',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5, 'Error, el nombre plipidico debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, el nombre plipidico debe contar con menos de 15 caracteres')]),
        ),
        migrations.AlterField(
            model_name='perfillipidico',
            name='observacion_plipidico',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, 'Error, la observacion debe contar con mas de 10 caracteres'), django.core.validators.MaxLengthValidator(150, 'Error, la observacion debe contar con menos de 150 caracteres')]),
        ),
    ]
