# Generated by Django 3.1.4 on 2021-01-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0002_auto_20210120_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coagulacion',
            name='observaciones_coagulacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coagulacion',
            name='porc_protrombina',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='coagulacion',
            name='tiempo_protrombina',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='glicemia',
            name='glicemia_120min',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='glicemia',
            name='glicemia_basal',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
