# Generated by Django 3.1.4 on 2021-01-21 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0003_auto_20210120_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rutUsuario', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=45)),
                ('staff', models.BooleanField()),
                ('usuario', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='glicemia',
            name='glicemia_120min',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.CreateModel(
            name='PerfilLipidico',
            fields=[
                ('id_plipidico', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_plipidico', models.DateTimeField()),
                ('nombre_plipidico', models.CharField(default='Examen de Perfil Lipidico', max_length=15)),
                ('colesterol', models.DecimalField(decimal_places=1, max_digits=2)),
                ('colesterol_ldl', models.DecimalField(decimal_places=1, max_digits=2)),
                ('colesterol_hdl', models.DecimalField(decimal_places=1, max_digits=2)),
                ('trigliceridos', models.DecimalField(decimal_places=1, max_digits=2)),
                ('observacion_plipidico', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilBioquimico',
            fields=[
                ('id_pbioquimico', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_pbioquimico', models.DateTimeField()),
                ('nombre_pbioquimico', models.CharField(default='Examen de Perfil Bioquimico', max_length=15)),
                ('glucosa', models.DecimalField(decimal_places=1, max_digits=2)),
                ('nitrogeno_ureico', models.DecimalField(decimal_places=1, max_digits=2)),
                ('calcio', models.DecimalField(decimal_places=1, max_digits=2)),
                ('fosforo', models.DecimalField(decimal_places=1, max_digits=2)),
                ('proteinas_totales', models.DecimalField(decimal_places=1, max_digits=2)),
                ('albumina', models.DecimalField(decimal_places=1, max_digits=2)),
                ('colesterol_total', models.DecimalField(decimal_places=1, max_digits=2)),
                ('acido_urico', models.DecimalField(decimal_places=1, max_digits=2)),
                ('fosfatas_alcalinas', models.DecimalField(decimal_places=1, max_digits=2)),
                ('bilirrubina_total', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ldh', models.DecimalField(decimal_places=1, max_digits=2)),
                ('got_ast', models.DecimalField(decimal_places=1, max_digits=2)),
                ('creatinina', models.DecimalField(decimal_places=1, max_digits=2)),
                ('observaciones_pbioquimico', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Orina',
            fields=[
                ('id_orina', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_orina', models.DateTimeField()),
                ('nombre_orina', models.CharField(default='Examen de Orina', max_length=15)),
                ('color', models.CharField(max_length=25)),
                ('densidad', models.DecimalField(decimal_places=1, max_digits=2)),
                ('glucosa', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cetonas', models.DecimalField(decimal_places=1, max_digits=2)),
                ('urobilinogeno', models.DecimalField(decimal_places=1, max_digits=2)),
                ('billirubina', models.DecimalField(decimal_places=1, max_digits=2)),
                ('observaciones_orina', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Hemograma',
            fields=[
                ('id_hemograma', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha_hemograma', models.DateTimeField()),
                ('nombre_hemograma', models.CharField(default='Examen de Hemograma', max_length=100)),
                ('eritrocito', models.DecimalField(decimal_places=1, max_digits=2)),
                ('leucocitos', models.DecimalField(decimal_places=1, max_digits=2)),
                ('hemoglobina', models.DecimalField(decimal_places=1, max_digits=2)),
                ('hematocrito', models.DecimalField(decimal_places=1, max_digits=2)),
                ('vcm', models.DecimalField(decimal_places=1, max_digits=2)),
                ('chcm', models.DecimalField(decimal_places=1, max_digits=2)),
                ('plaquetas', models.DecimalField(decimal_places=1, max_digits=2)),
                ('observaciones_hemograma', models.CharField(default='Parametros normales', max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('fecha_diagnostico', models.DateTimeField(default=None, primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=100)),
                ('fk_rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='coagulacion',
            name='fk_rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario'),
        ),
        migrations.AddField(
            model_name='glicemia',
            name='fk_rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario'),
        ),
    ]
