# Generated by Django 2.2.17 on 2021-01-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0003_auto_20210121_1028'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hemograma',
            table='Hemograma',
        ),
        migrations.AlterModelTable(
            name='perfilbioquimico',
            table='PerfilLipidico',
        ),
    ]
