# Generated by Django 2.2.17 on 2021-01-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0003_auto_20210120_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rutUsuario',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
    ]
