# Generated by Django 3.1.4 on 2021-01-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0004_auto_20210120_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coagulacion',
            old_name='fk_rutUsuario',
            new_name='rutUsuario',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='fk_rutUsuario',
            new_name='rutUsuario',
        ),
        migrations.RenameField(
            model_name='hemograma',
            old_name='fk_rutUsuario',
            new_name='rutUsuario',
        ),
        migrations.RenameField(
            model_name='orina',
            old_name='fk_rutUsuario',
            new_name='rutUsuario',
        ),
        migrations.RenameField(
            model_name='perfilbioquimico',
            old_name='fk_rutUsuario',
            new_name='rutUsuario',
        ),
        migrations.RenameField(
            model_name='perfillipidico',
            old_name='fk_rutUsuario',
            new_name='rutUsuario',
        ),
        migrations.RemoveField(
            model_name='glicemia',
            name='fk_rutUsuario',
        ),
        migrations.AddField(
            model_name='glicemia',
            name='rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario'),
        ),
        migrations.AlterField(
            model_name='coagulacion',
            name='fecha_coagulacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha_diagnostico',
            field=models.DateField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='glicemia',
            name='fecha_glicemia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='fecha_hemograma',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orina',
            name='fecha_orina',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='perfilbioquimico',
            name='fecha_pbioquimico',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='perfillipidico',
            name='fecha_plipidico',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rutUsuario',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
    ]
