# Generated by Django 2.2.17 on 2021-01-21 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0004_auto_20210120_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCBV',
            fields=[
                ('rutUsuario', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10, 'el rut debe tener entre 9 y 10 caracteres incluido el guion'), django.core.validators.MinValueValidator(9, 'el rut debe tener entre 9 y 10 caracteres incluido el guion')])),
                ('nombre', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(3, 'el nombre debe tener al menos 3 letras ')])),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(10, 'debe tener al menos 10 años')])),
                ('direccion', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(3, 'la direccion debe tener al menos 3 letras ')])),
                ('staff', models.BooleanField()),
                ('usuario', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(3, 'el usuario debe tener al menos 3 letras ')])),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(3, 'el password debe tener al menos 3 letras ')])),
            ],
        ),
    ]
