# Generated by Django 3.1.4 on 2021-01-21 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0005_auto_20210120_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glicemia',
            name='observaciones_glicemia',
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha_diagnostico',
            field=models.DateTimeField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(10, 'Error, la dirección debe contener más de 10 caracteres'), django.core.validators.MaxLengthValidator(45, 'Error, la dirección puede contener hasta 45 caracteres ')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Error, la edad no puede ser menor a 1 '), django.core.validators.MaxValueValidator(99, 'Error, la edad no puede tener menos más de 3 números')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(10, 'El nombre debe tener minimo 10 caracteres'), django.core.validators.MaxLengthValidator(45, 'El nombre puede tener hasta 45 caracteres')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(6, 'Error, la contraseña debe contener más de 6 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, la dirección puede contener hasta 15 caracteres ')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rutUsuario',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9, 'Ingresar dni en el siguiente formato 77111666-5'), django.core.validators.MaxLengthValidator(10, 'Ingresar dni en el siguiente formato 77111666-5')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5, 'Error, el usuario debe tener mínimo 5 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, el usuario debe contener hasta 15 caracteres ')]),
        ),
    ]
