# Generated by Django 3.1.5 on 2021-01-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0005_auto_20210120_1834'),
        ('app_med2', '0002_auto_20210120_1831'),
    ]

    operations = [
    ]
