# Generated by Django 2.2.17 on 2021-01-21 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0005_usuariocbv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coagulacion',
            name='fk_rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.UsuarioCBV'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='fk_rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.UsuarioCBV'),
        ),
        migrations.AlterField(
            model_name='glicemia',
            name='fk_rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.UsuarioCBV'),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='fk_rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.UsuarioCBV'),
        ),
        migrations.AlterField(
            model_name='orina',
            name='fk_rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.UsuarioCBV'),
        ),
        migrations.AlterField(
            model_name='perfilbioquimico',
            name='fk_rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.UsuarioCBV'),
        ),
        migrations.AlterField(
            model_name='perfillipidico',
            name='fk_rutUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.UsuarioCBV'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
