# Generated by Django 3.1.5 on 2021-01-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0006_auto_20210121_1244'),
        ('app_med2', '0006_merge_20210120_2332'),
    ]

    operations = [
    ]
