# Generated by Django 3.1.4 on 2021-01-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0007_auto_20210121_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coagulacion',
            name='fecha_coagulacion',
        ),
    ]
