# Generated by Django 3.1.5 on 2021-01-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0007_merge_20210121_1720'),
        ('app_med2', '0003_auto_20210121_1028'),
    ]

    operations = [
    ]
