# Generated by Django 3.1.5 on 2021-01-27 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0008_glicemia_observaciones_glicemia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('rutFamiliar', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9, 'Ingresar dni en el siguiente formato 77111666-5'), django.core.validators.MaxLengthValidator(10, 'Ingresar dni en el siguiente formato 77111666-5')])),
                ('nombre', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(10, 'El nombre debe tener minimo 10 caracteres'), django.core.validators.MaxLengthValidator(45, 'El nombre puede tener hasta 45 caracteres')])),
                ('direccion', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(10, 'Error, la dirección debe contener más de 10 caracteres'), django.core.validators.MaxLengthValidator(45, 'Error, la dirección puede contener hasta 45 caracteres ')])),
                ('usuario', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5, 'Error, el usuario debe tener mínimo 5 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, el usuario debe contener hasta 15 caracteres ')])),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(6, 'Error, la contraseña debe contener más de 6 caracteres'), django.core.validators.MaxLengthValidator(15, 'Error, la dirección puede contener hasta 15 caracteres ')])),
                ('rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_med2.usuario')),
            ],
        ),
    ]
