# Generated by Django 3.1.4 on 2021-01-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0008_glicemia_observaciones_glicemia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='sin asignar', max_length=50),
        ),
    ]
