# Generated by Django 2.2.17 on 2021-01-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0009_auto_20210120_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocbv',
            name='rutUsuario',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
    ]
