# Generated by Django 3.1.5 on 2021-01-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0009_familiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
