# Generated by Django 3.1.5 on 2021-01-27 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0011_auto_20210127_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
