# Generated by Django 3.1.5 on 2021-01-28 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_med2', '0013_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default=None, max_length=45, validators=[django.core.validators.MinLengthValidator(10, 'El nombre debe tener minimo 10 caracteres'), django.core.validators.MaxLengthValidator(45, 'El nombre puede tener hasta 45 caracteres')]),
        ),
    ]
